export const LOADING_TIPS = [
  "Greatness takes time… and a fast internet connection.",
  "Did you hydrate today? Your voice matters.",
  "Fun fact: The fear of public speaking is called glossophobia.",
  "Warming up your charisma engine…",
  "Preparing the stage for your brilliance...",
  "Even the best speakers need a dramatic pause…",
  "Checking mic levels... Testing, testing... 1, 2, YOU!",
  "Behind every great speech is a loading spinner.",
  "Aligning your confidence chakras",
  "Powering up your persuasive powers",
  "Downloading applause. This may take a moment...",
  "The audience is getting seated. Please hold.",
  "Applying your charisma filter...",
  "Searching for your inner TED Talk.",
  "Installing virtual standing ovations...",
  "Getting your 'um's and 'uh's under control...",
  "Unmuting your potential...",
  "Almost there… your voice is warming up!",
];
